export interface EngineConfig {
  TOTAL_POSSESSIONS: number;
  ENERGY_DRAIN_PER_MINUTE: number;
  WEEKLY_ENERGY_RECOVERY: number;
  BIG_MOMENT_CHANCE: number;
  GLOBAL_HOME_ADVANTAGE: number;
  PHASE_ONE_FAIL_ESCAPE_CHANCE: number;
  ATTACKING_THROUGH_BALL_BASE_CHANCE: number;
  MISS_EVENT_POOL_SIZE: number;
  WIDE_ROUTE_BASE_CHANCE: number;
  WIDE_ROUTE_MIN_CHANCE: number;
  WIDE_ROUTE_MAX_CHANCE: number;
  BIG_MOMENT_MIN_CHANCE: number;
  BIG_MOMENT_MAX_CHANCE: number;
  ATTACKING_MENTALITY_SHOOTING_MULTIPLIER: number;
  ATTACKING_MENTALITY_PASSING_MULTIPLIER: number;
  DEFENSIVE_MENTALITY_SHOOTING_MULTIPLIER: number;
  DEFENSIVE_MENTALITY_PASSING_MULTIPLIER: number;
  DEFENDER_ATTACKING_MENTALITY_MULTIPLIER: number;
  DEFENDER_DEFENSIVE_MENTALITY_MULTIPLIER: number;
  SHORT_PASSING_MULTIPLIER: number;
  DIRECT_PASSING_MULTIPLIER: number;
  MIXED_PASSING_MULTIPLIER: number;
  SHORT_PASS_THROUGH_BALL_CHANCE: number;
  DIRECT_PASS_THROUGH_BALL_CHANCE: number;
  MIXED_PASS_THROUGH_BALL_CHANCE: number;
  DEFENSIVE_PRESS_HIGH_MULTIPLIER: number;
  DEFENSIVE_PRESS_NONE_MULTIPLIER: number;
  INTERCEPT_HIGH_LINE_MULTIPLIER: number;
  INTERCEPT_DEEP_LINE_MULTIPLIER: number;
  INTERCEPT_PRESS_HIGH_MULTIPLIER: number;
  INTERCEPT_PRESS_NONE_MULTIPLIER: number;
  TEMPO_FAST_BIG_MOMENT_MULTIPLIER: number;
  TEMPO_SLOW_BIG_MOMENT_MULTIPLIER: number;
  DEFENDER_PRESS_HIGH_BIG_MOMENT_MULTIPLIER: number;
  DEFENDER_PRESS_NONE_BIG_MOMENT_MULTIPLIER: number;
  STAT_COMPRESSION_BASE: number;
  STAT_COMPRESSION_FACTOR: number;
  RATING_CURVE_GAMMA: number;
  DUEL_LUCK_MIDFIELD: number;
  DUEL_LUCK_ATTACK: number;
  DUEL_LUCK_SHOOTING: number;
  FOUL_CHANCE: number;
  RED_CARD_CHANCE: number;
  SECOND_YELLOW_RED_CHANCE: number;
  STEAMROLL: readonly { margin: number; bonus: number }[];
  SUBS: {
    BASE_MAX: number;
    CHASING_BONUS_RANGE: number;
    LEADING_BONUS_RANGE: number;
    ATTACKING_BONUS_RANGE: number;
    DEFENSIVE_BONUS_RANGE: number;
    CHASING_MINUTE_RANGE: readonly [number, number];
    LEADING_MINUTE_RANGE: readonly [number, number];
    BALANCED_MINUTE_RANGE: readonly [number, number];
    CHECKPOINTS: readonly number[];
  };
  POST_MATCH: {
    BASE_ENERGY_DRAIN: number;
    TEMPO_FAST_DRAIN_MULTIPLIER: number;
    PRESSING_HIGH_DRAIN_MULTIPLIER: number;
    BASE_MATCH_RATING: number;
    MATCH_RATING_RANDOM_SPREAD: number;
    MATCH_RATING_RANDOM_SHIFT: number;
    MATCH_RATING_WIN_BONUS: number;
    MATCH_RATING_DRAW_BONUS: number;
    MATCH_RATING_LOSS_PENALTY: number;
    MATCH_RATING_CLEAN_SHEET_BONUS: number;
    MATCH_RATING_SHORT_CAMEO_PENALTY: number;
  };
  TRANSFER_MARKET: {
    LIST_MIN_MINUTES_SHARE: number;
    POOR_FORM_CHANCE: number;
    VETERAN_CHANCE: number;
    BACKUP_CHANCE: number;
    EARLY_BUY_CHANCE: number;
    NORMAL_BUY_CHANCE: number;
  };
  CONTRACTS: {
    YOUNG_AGE_THRESHOLD: number;
    PEAK_AGE_THRESHOLD: number;
    VETERAN_AGE_THRESHOLD: number;
    YOUNG_WAGE_MULTIPLIER: number;
    VETERAN_WAGE_MULTIPLIER: number;
    PEAK_WAGE_MULTIPLIER: number;
  };
  FIRST_ATTACK_HOME_BIAS: number;
  KNOCKOUT: {
    PENALTY_ADVANTAGE_MULTIPLIER: number;
  };
}

export const ENGINE_CONFIG: EngineConfig = {
  TOTAL_POSSESSIONS: 28,
  ENERGY_DRAIN_PER_MINUTE: 0.25,
  WEEKLY_ENERGY_RECOVERY: 50,

  BIG_MOMENT_CHANCE: 0.35,
  GLOBAL_HOME_ADVANTAGE: 1.04,
  PHASE_ONE_FAIL_ESCAPE_CHANCE: 0.12,
  ATTACKING_THROUGH_BALL_BASE_CHANCE: 0.35,
  MISS_EVENT_POOL_SIZE: 4,
  WIDE_ROUTE_BASE_CHANCE: 0.28,
  WIDE_ROUTE_MIN_CHANCE: 0.15,
  WIDE_ROUTE_MAX_CHANCE: 0.82,
  BIG_MOMENT_MIN_CHANCE: 0.2,
  BIG_MOMENT_MAX_CHANCE: 0.8,

  ATTACKING_MENTALITY_SHOOTING_MULTIPLIER: 1.1,
  ATTACKING_MENTALITY_PASSING_MULTIPLIER: 1.05,
  DEFENSIVE_MENTALITY_SHOOTING_MULTIPLIER: 0.85,
  DEFENSIVE_MENTALITY_PASSING_MULTIPLIER: 1.05,
  DEFENDER_ATTACKING_MENTALITY_MULTIPLIER: 0.88,
  DEFENDER_DEFENSIVE_MENTALITY_MULTIPLIER: 1.15,
  SHORT_PASSING_MULTIPLIER: 1.15,
  DIRECT_PASSING_MULTIPLIER: 0.85,
  MIXED_PASSING_MULTIPLIER: 1.0,
  SHORT_PASS_THROUGH_BALL_CHANCE: 0.25,
  DIRECT_PASS_THROUGH_BALL_CHANCE: 0.75,
  MIXED_PASS_THROUGH_BALL_CHANCE: 0.5,
  DEFENSIVE_PRESS_HIGH_MULTIPLIER: 1.12,
  DEFENSIVE_PRESS_NONE_MULTIPLIER: 0.96,
  INTERCEPT_HIGH_LINE_MULTIPLIER: 1.05,
  INTERCEPT_DEEP_LINE_MULTIPLIER: 0.95,
  INTERCEPT_PRESS_HIGH_MULTIPLIER: 1.08,
  INTERCEPT_PRESS_NONE_MULTIPLIER: 0.95,
  TEMPO_FAST_BIG_MOMENT_MULTIPLIER: 1.01,
  TEMPO_SLOW_BIG_MOMENT_MULTIPLIER: 0.99,
  DEFENDER_PRESS_HIGH_BIG_MOMENT_MULTIPLIER: 0.99,
  DEFENDER_PRESS_NONE_BIG_MOMENT_MULTIPLIER: 1.01,

  STAT_COMPRESSION_BASE: 80,
  STAT_COMPRESSION_FACTOR: 0.3,
  RATING_CURVE_GAMMA: 1.0,
  DUEL_LUCK_MIDFIELD: 32,
  DUEL_LUCK_ATTACK: 28,
  DUEL_LUCK_SHOOTING: 24,

  STEAMROLL: [
    { margin: 2, bonus: 1.1 },
    { margin: 3, bonus: 1.25 },
  ],

  FOUL_CHANCE: 0.28,
  RED_CARD_CHANCE: 0.015,
  SECOND_YELLOW_RED_CHANCE: 0.12,

  SUBS: {
    BASE_MAX: 2,
    CHASING_BONUS_RANGE: 3,
    LEADING_BONUS_RANGE: 3,
    ATTACKING_BONUS_RANGE: 2,
    DEFENSIVE_BONUS_RANGE: 2,
    CHASING_MINUTE_RANGE: [50, 78] as const,
    LEADING_MINUTE_RANGE: [60, 88] as const,
    BALANCED_MINUTE_RANGE: [55, 84] as const,
    CHECKPOINTS: [56, 66, 76, 84] as readonly number[],
  },

  POST_MATCH: {
    BASE_ENERGY_DRAIN: 25,
    TEMPO_FAST_DRAIN_MULTIPLIER: 1.3,
    PRESSING_HIGH_DRAIN_MULTIPLIER: 1.3,
    BASE_MATCH_RATING: 6.0,
    MATCH_RATING_RANDOM_SPREAD: 1.2,
    MATCH_RATING_RANDOM_SHIFT: -0.4,
    MATCH_RATING_WIN_BONUS: 0.8,
    MATCH_RATING_DRAW_BONUS: 0.2,
    MATCH_RATING_LOSS_PENALTY: 0.6,
    MATCH_RATING_CLEAN_SHEET_BONUS: 1.0,
    MATCH_RATING_SHORT_CAMEO_PENALTY: 0.3,
  },

  TRANSFER_MARKET: {
    LIST_MIN_MINUTES_SHARE: 0.3,
    POOR_FORM_CHANCE: 0.45,
    VETERAN_CHANCE: 0.18,
    BACKUP_CHANCE: 0.03,
    EARLY_BUY_CHANCE: 0.15,
    NORMAL_BUY_CHANCE: 0.35,
  },

  CONTRACTS: {
    YOUNG_AGE_THRESHOLD: 23,
    PEAK_AGE_THRESHOLD: 29,
    VETERAN_AGE_THRESHOLD: 33,
    YOUNG_WAGE_MULTIPLIER: 1.15,
    VETERAN_WAGE_MULTIPLIER: 1.18,
    PEAK_WAGE_MULTIPLIER: 1.08,
  },

  FIRST_ATTACK_HOME_BIAS: 0.5,

  KNOCKOUT: {
    PENALTY_ADVANTAGE_MULTIPLIER: 50,
  },
};
