export const ENGINE_CONFIG = {
  // MATCH TIMING & PACING
  TOTAL_POSSESSIONS: 28, // Scaled down from 35 to drastically reduce excessive shot attempts
  ENERGY_DRAIN_PER_MINUTE: 0.25, // Energy lost per minute played
  WEEKLY_ENERGY_RECOVERY: 50, // Energy regained after a week

  // SCORING & CHANCES
  BIG_MOMENT_CHANCE: 0.35, // Drastically reduced from 0.52
  GLOBAL_HOME_ADVANTAGE: 1.04, // Slightly tuned
  PHASE_ONE_FAIL_ESCAPE_CHANCE: 0.12, // Cut from 0.25 so midfield walls work better
  ATTACKING_THROUGH_BALL_BASE_CHANCE: 0.35,
  MISS_EVENT_POOL_SIZE: 4,
  WIDE_ROUTE_BASE_CHANCE: 0.28,
  WIDE_ROUTE_MIN_CHANCE: 0.15,
  WIDE_ROUTE_MAX_CHANCE: 0.82,
  BIG_MOMENT_MIN_CHANCE: 0.2,
  BIG_MOMENT_MAX_CHANCE: 0.8,

  // TACTICAL MODIFIERS
  ATTACKING_MENTALITY_SHOOTING_MULTIPLIER: 1.1,
  ATTACKING_MENTALITY_PASSING_MULTIPLIER: 1.05,
  DEFENSIVE_MENTALITY_SHOOTING_MULTIPLIER: 0.85,
  DEFENSIVE_MENTALITY_PASSING_MULTIPLIER: 1.05,
  DEFENDER_ATTACKING_MENTALITY_MULTIPLIER: 0.88,
  DEFENDER_DEFENSIVE_MENTALITY_MULTIPLIER: 1.15,
  SHORT_PASSING_MULTIPLIER: 1.15,
  DIRECT_PASSING_MULTIPLIER: 0.85,
  MIXED_PASSING_MULTIPLIER: 1.0,
  SHORT_PASS_THROUGH_BALL_CHANCE: 0.25,
  DIRECT_PASS_THROUGH_BALL_CHANCE: 0.75,
  MIXED_PASS_THROUGH_BALL_CHANCE: 0.5,
  DEFENSIVE_PRESS_HIGH_MULTIPLIER: 1.12,
  DEFENSIVE_PRESS_NONE_MULTIPLIER: 0.96,
  INTERCEPT_HIGH_LINE_MULTIPLIER: 1.05,
  INTERCEPT_DEEP_LINE_MULTIPLIER: 0.95,
  INTERCEPT_PRESS_HIGH_MULTIPLIER: 1.08,
  INTERCEPT_PRESS_NONE_MULTIPLIER: 0.95,
  TEMPO_FAST_BIG_MOMENT_MULTIPLIER: 1.01,
  TEMPO_SLOW_BIG_MOMENT_MULTIPLIER: 0.99,
  DEFENDER_PRESS_HIGH_BIG_MOMENT_MULTIPLIER: 0.99,
  DEFENDER_PRESS_NONE_BIG_MOMENT_MULTIPLIER: 1.01,

  // DUELS & VARIANCE
  STAT_COMPRESSION_BASE: 80, // Compress elite stat gaps to reduce team scoring extremes
  STAT_COMPRESSION_FACTOR: 0.4,
  RATING_CURVE_GAMMA: 1.0, // Optional non-linear stat curve (1.0 = linear)
  DUEL_LUCK_MIDFIELD: 29,
  DUEL_LUCK_ATTACK: 25,
  DUEL_LUCK_SHOOTING: 22,

  // ANTI-STEAMROLL (Desperation mechanics for trailing teams)
  STEAMROLL_MARGIN_1: 2,
  STEAMROLL_BONUS_1: 1.1,
  STEAMROLL_MARGIN_2: 3,
  STEAMROLL_BONUS_2: 1.25,

  // DISCIPLINE
  MIDFIELD_FOUL_CHANCE: 0.69,
  FOUL_CHANCE: 0.30,
  RED_CARD_CHANCE: 0.015,
  SECOND_YELLOW_RED_CHANCE: 0.12,

  // SUBSTITUTION HEURISTICS
  SUBS_BASE_MAX: 2,
  SUBS_CHASING_BONUS_RANGE: 3,
  SUBS_LEADING_BONUS_RANGE: 3,
  SUBS_ATTACKING_BONUS_RANGE: 2,
  SUBS_DEFENSIVE_BONUS_RANGE: 2,
  SUBS_CHASING_MINUTE_RANGE: [50, 78] as const,
  SUBS_LEADING_MINUTE_RANGE: [60, 88] as const,
  SUBS_BALANCED_MINUTE_RANGE: [55, 84] as const,

  // POST-MATCH ACCOUNTING
  BASE_POST_MATCH_ENERGY_DRAIN: 25,
  TEMPO_FAST_DRAIN_MULTIPLIER: 1.3,
  PRESSING_HIGH_DRAIN_MULTIPLIER: 1.3,
  BASE_MATCH_RATING: 6.0,
  MATCH_RATING_RANDOM_SPREAD: 1.2,
  MATCH_RATING_RANDOM_SHIFT: -0.4,
  MATCH_RATING_WIN_BONUS: 0.8,
  MATCH_RATING_DRAW_BONUS: 0.2,
  MATCH_RATING_LOSS_PENALTY: 0.6,
  MATCH_RATING_CLEAN_SHEET_BONUS: 1.0,
  MATCH_RATING_SHORT_CAMEO_PENALTY: 0.3,

  // TRANSFER MARKET HEURISTICS
  TRANSFER_LIST_MIN_MINUTES_SHARE: 0.3,
  TRANSFER_LIST_POOR_FORM_CHANCE: 0.45,
  TRANSFER_LIST_VETERAN_CHANCE: 0.18,
  TRANSFER_LIST_BACKUP_CHANCE: 0.03,
  TRANSFER_EARLY_BUY_CHANCE: 0.15,
  TRANSFER_NORMAL_BUY_CHANCE: 0.35,
};
