import { StyleSheet } from 'react-native';
import { color } from '@/src/design/tokens';

export const matchStyles = StyleSheet.create({
  topNav: {
      paddingHorizontal: 20,
      paddingTop: 10,
      alignItems: 'flex-end',
  },
  exitBtn: {
      padding: 8,
  },
  exitText: {
      color: color.danger.base,
      fontWeight: 'bold',
      fontSize: 16,
  },
  scrollContent: {
      padding: 24,
      paddingTop: 10,
  },
  headerTitle: {
    color: color.text.primary,
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 4,
  },
  stadiumText: {
      color: color.text.faint,
      fontSize: 14,
      textAlign: 'center',
      fontWeight: '600',
      marginBottom: 12,
      letterSpacing: 1,
  },
  minuteClock: {
      color: color.danger.base,
      fontSize: 32,
      fontWeight: '900',
      textAlign: 'center',
      marginBottom: 20,
  },
  scoreboard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: color.bg.card,
    padding: 20,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: color.border.default,
  },
  teamBox: {
    flex: 1,
    alignItems: 'center',
  },
  teamName: {
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 8,
  },
  score: {
    color: color.text.primary,
    fontSize: 42,
    fontWeight: '900',
  },
  vsBox: {
    paddingHorizontal: 16,
  },
  vsText: {
    color: color.text.faint,
    fontSize: 16,
    fontWeight: '900',
  },
  penaltiesNote: {
    color: color.warning.fg,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 12,
  },
  summaryPanel: {
    marginTop: 20,
    backgroundColor: color.bg.card,
    borderWidth: 1,
    borderColor: color.border.default,
    padding: 14,
  },
  summaryTitle: {
    color: color.text.primary,
    fontSize: 14,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: color.border.subtle,
  },
  statValue: {
    flex: 1,
    color: color.text.primary,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  statLabel: {
    flex: 2,
    color: color.text.muted,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  motmBox: {
    marginTop: 14,
    marginBottom: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: color.border.subtle,
  },
  motmName: {
    color: color.warning.fg,
    fontSize: 18,
    fontWeight: '900',
  },
  motmMeta: {
    color: color.text.muted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  ratingsGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  ratingsCol: {
    flex: 1,
  },
  compactRatingsGrid: { flexDirection: 'column' },
  compactRatingsCol: { flexGrow: 0, flexShrink: 0, flexBasis: 'auto', width: '100%' },
  compactRatingText: { fontSize: 13 },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: color.border.subtle,
  },
  ratingName: {
    flex: 1,
    minWidth: 0,
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '700',
  },
  ratingMeta: {
    color: color.text.primary,
    fontSize: 11,
    fontWeight: '900',
    minWidth: 32,
    textAlign: 'right',
  },
  logBox: {
    marginTop: 24,
    backgroundColor: color.bg.card,
    padding: 16,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: color.border.default,
    minHeight: 120,
  },
  logText: {
    color: color.text.muted,
    fontSize: 12,
    marginBottom: 4,
  },
  logTextLatest: {
    color: color.accent.primary,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  lineupRow: {
      flexDirection: 'row',
      marginTop: 24,
      justifyContent: 'space-between',
  },
  lineupCol: {
      flex: 1,
  },
  lineupHeader: {
      fontSize: 14,
      fontWeight: '900',
      marginBottom: 12,
      textTransform: 'uppercase',
  },
  lineupPlayerName: {
      color: color.text.secondary,
      fontSize: 12,
      marginBottom: 4,
  },
  buttonContainer: {
    marginTop: 48,
    paddingBottom: 40,
  },
  halfTimeActions: {
    gap: 12,
    alignItems: 'center',
  },
  btnSimulate: {
    backgroundColor: color.accent.primary,
    paddingVertical: 10,
    paddingHorizontal: 32,
    borderRadius: 0,
    alignItems: 'center',
    alignSelf: 'center',
    minWidth: 200,
  },
  btnPause: {
    backgroundColor: color.warning.base,
    paddingVertical: 10,
    paddingHorizontal: 32,
    borderRadius: 0,
    alignItems: 'center',
    alignSelf: 'center',
    minWidth: 200,
  },
  btnContinue: {
    backgroundColor: color.success.base,
    paddingVertical: 10,
    paddingHorizontal: 32,
    borderRadius: 0,
    alignItems: 'center',
    alignSelf: 'center',
    minWidth: 200,
  },
  btnText: {
    color: color.bg.screen,
    fontSize: 16,
    fontWeight: '900',
  },
  lineupPosPill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 0,
    marginRight: 6,
    minWidth: 32,
    alignItems: 'center',
  },
  lineupPosText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '900',
  },
  lineupPlayerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  liveControlPanel: {
    borderWidth: 1,
    borderColor: color.border.default,
    backgroundColor: color.bg.card,
    padding: 12,
    marginBottom: 16,
  },
  liveControlHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  liveControlTitle: {
    color: color.text.primary,
    fontSize: 16,
    fontWeight: '900',
  },
  liveControlMeta: {
    color: color.text.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  shapeButton: {
    borderWidth: 1,
    borderColor: color.accent.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  shapeButtonText: {
    color: color.accent.primary,
    fontSize: 12,
    fontWeight: '900',
  },
  subPickerGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  subPickerCol: {
    flex: 1,
  },
  subPickerTitle: {
    color: color.text.primary,
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  subPlayerRow: {
    borderWidth: 1,
    borderColor: color.border.subtle,
    paddingHorizontal: 8,
    paddingVertical: 7,
    marginBottom: 6,
  },
  subPlayerSelected: {
    borderColor: color.accent.primary,
    backgroundColor: color.accent.dim,
  },
  subPlayerName: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '800',
  },
  subPlayerMeta: {
    color: color.text.faint,
    fontSize: 10,
    fontWeight: '800',
    marginTop: 2,
  },
  pendingSubsBox: {
    marginTop: 10,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: color.border.subtle,
  },
  pendingSubText: {
    color: color.text.muted,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 3,
  },
  subActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
});
