// Aggregated regression runner. Checks are split by domain into
// ./calendar, ./match, ./transfer, ./board, ./persistence, ./live-match, ./squad.
// Execution order matches the original scripts/regression_checks.ts runner.
import { checkFormationSlotLookupUsesExactFormation, checkFormationMapRejectsWrongPositions, checkSeededFormationDiversity, checkRosterSizeConstraints, checkUnavailableBenchPlayersCanBeRemoved, checkRecoveredSelectedBenchDoesNotOverflow, checkLineupActionsPreserveBenchLimit, checkLineupInboxActionFiltersStaleFormationMap, checkTacticalAdaptationRunsOncePerPlayedCount, checkTacticalAdaptationIgnoresUnavailablePlayers } from './squad';
import { checkCleanSheetWindows, checkPossessionFlowIsNotStrictAlternation, checkBranchGuards, checkSanityMatchScores, checkDisciplineRatesArePlausible, checkQuickSimMatchSummaryIncludesStatsAndRatings, checkMatchRatingsIncludeIndividualOutput, checkCleanSheetRatingsUsePlayerWindow, checkPenaltyShootoutUsesIndividualKicks, checkQuickSimKnockoutUsesExtraTimeBeforePenalties, checkLeaguePlayoffFixtureDoesNotChangeTableStats } from './match';
import { checkLiveSentOffMinutes, checkLiveSubstitutionsApplyBeforeFullTime, checkUserAiDoesNotSpendLiveSubstitutions, checkManualLiveSubstitutionAndShapeAreMatchLocal, checkManualLiveSubstitutionValidation, checkLiveMatchSummaryIncludesStatsAndRatings, checkLiveKnockoutExtraTimeTransition, checkActiveLiveMatchBlocksWeekAdvance, checkStaleLiveMatchRecovery, checkDirectFinishCompletesUnprocessedLiveMatch, checkZustandStoreLiveMatchCleanup } from './live-match';
import { checkCompetitionPanelHandlesMissingTeam, checkDivisionBootstrap, checkPromotionRelegation, checkSeasonReportsUseCompetitionLifecycleAndLeagueTables, checkSeasonEndProgressionUpdatesMatchAbility, checkSeasonRolloverReplenishesMinimumSquadAndGoalkeepers, checkEflPlayoffsAreScheduledAfterRegularSeason, checkEflPlayoffSemiFinalsUseAggregateTiebreak, checkRolloverWaitsForPlayoffFinal } from './calendar';
import { checkUserTeamProgressionDoesNotAdaptFormation, checkManagerProfilesLoaded, checkActiveCupRoundCountsAsReached, checkBoardObjectiveIdsAreStable, checkMidSeasonSackingTerminatesImmediately, checkNonTerminalSackingWarningDoesNotDismiss, checkSeasonEndSackingUsesSharedThreshold, checkUiContractsMatchEngineState, checkInitialGameSetupCanBeSeeded, checkStoreInitializesSelectedTeamDefaults } from './board';
import { checkAcceptCounterMovesPlayerAndMarksNegotiationAccepted, checkActiveNegotiationsCanBeWithdrawnInUi, checkApproachCoreNeededPlayerRejectsWithoutNegotiation, checkApproachUnlistedBackupCreatesPendingNegotiation, checkListedUnderAskCreatesCounterNegotiationWithoutMove, checkManualTransfersRespectWindow, checkManualTransfersRejectNonFiniteMoney, checkManualFreeAgentSigningMovesPlayerDuringWindow, checkManualFreeAgentSigningWorksOutsideWindow, checkManualFreeAgentSigningRejectsFullSquad, checkRivalBidWinsWhenUserDoesNotMatch, checkWeeklyNegotiationsExpireAfterDeadline, checkAiTransferListingsExpireOutsideWindow, checkAiBuyerAtMaximumSquadSizeCannotBuy, checkAiSignsFreeAgentForUrgentSquadNeed, checkAiStaleListedTargetIsRevalidated, checkEliteAiRejectsUnderStandardTarget, checkExperiencedAiPrefersOlderEqualTarget, checkAiTransferRespectsOperatingWageAffordability, checkContractDeparturesPreferViableDestinations, checkSimultaneousExpiriesRecomputeAgainstProvisionalSquad } from './transfer';
import { checkFreezeRecoveryControlsAreVisible, checkStaleFormationMapRecoveryModel, checkFreeAgentSaveReloadEquivalence, checkValidationCatchesPastUnplayedFixturesAndNonFiniteFinances } from './persistence';
import { checkWeeklyTrainingFocusRaisesFocusedStat, checkTrainingRespectsPotentialCap, checkSeasonEndProgressionRespectsPotentialCap, checkYouthIntakeAssignsHiddenPotential } from './training';
import { checkPlayerRoleCompatibilityMatrix, checkPlayerRoleEnergyDrainModifiers, checkRolePickerShowsRoleEffects, checkSlotKeyedPlayerRoleLookup, checkPlayerRolesAdjustShapeProfile, checkMatchRuntimeUsesPlayerRoles } from './roles';
import { checkRelentlessTraitReducesFatiguePenalty, checkSeededPlayersNormalizeTraits, checkTraitBonusesExposeMechanicalEffects, checkTraitRegistryCoversSeededTraits, checkTraitTrainingFocusAddsXp } from './traits';
import { checkWeeklyProgressionAppliesRevenueBreakdown, checkWeeklyRevenueUsesDivisionAndSponsorRates } from './finance';

const runRegressionChecks = () => {
  console.log('--- ENGINE REGRESSION CHECKS ---');
  checkFormationSlotLookupUsesExactFormation();
  console.log('[OK] Exact formation slot lookup passed');
  checkCleanSheetWindows();
  console.log('[OK] Clean-sheet window checks passed');
  checkLiveSentOffMinutes();
  console.log('[OK] Live sent-off minute check passed');
  checkPossessionFlowIsNotStrictAlternation();
  console.log('[OK] Possession flow variability guard passed');
  checkLiveSubstitutionsApplyBeforeFullTime();
  console.log('[OK] Live in-match substitution check passed');
  checkUserAiDoesNotSpendLiveSubstitutions();
  console.log('[OK] User live AI-substitution guard passed');
  checkManualLiveSubstitutionAndShapeAreMatchLocal();
  console.log('[OK] Manual live substitution and shape locality passed');
  checkManualLiveSubstitutionValidation();
  console.log('[OK] Manual live substitution validation passed');
  checkLiveMatchSummaryIncludesStatsAndRatings();
  console.log('[OK] Live match summary checks passed');
  checkLiveKnockoutExtraTimeTransition();
  console.log('[OK] Live extra-time transition passed');
  checkActiveLiveMatchBlocksWeekAdvance();
  console.log('[OK] Active live match week-advance guard passed');
  checkStaleLiveMatchRecovery();
  console.log('[OK] Stale live-match recovery passed');
  checkDirectFinishCompletesUnprocessedLiveMatch();
  console.log('[OK] Direct live-match finish completion passed');
  checkCompetitionPanelHandlesMissingTeam();
  console.log('[OK] Competition panel missing-team fallback passed');
  checkFreezeRecoveryControlsAreVisible();
  console.log('[OK] Freeze recovery controls passed');
  checkBranchGuards();
  console.log('[OK] Second-yellow and shape parity guards passed');
  checkUserTeamProgressionDoesNotAdaptFormation();
  console.log('[OK] User team tactical adaptation guard passed');
  checkManagerProfilesLoaded();
  console.log('[OK] Manager profile loading passed');
  checkDivisionBootstrap();
  console.log('[OK] Division bootstrap check passed');
  checkPromotionRelegation();
  console.log('[OK] Promotion and relegation checks passed');
  checkEflPlayoffsAreScheduledAfterRegularSeason();
  console.log('[OK] EFL play-off scheduling checks passed');
  checkEflPlayoffSemiFinalsUseAggregateTiebreak();
  console.log('[OK] EFL play-off aggregate tiebreak checks passed');
  checkRolloverWaitsForPlayoffFinal();
  console.log('[OK] Play-off season extension check passed');
  checkStaleFormationMapRecoveryModel();
  console.log('[OK] Stale formation-map recovery model passed');
  checkFormationMapRejectsWrongPositions();
  console.log('[OK] Wrong-position formation-map recovery passed');
  checkActiveCupRoundCountsAsReached();
  console.log('[OK] Active cup-round objective recognition passed');
  checkBoardObjectiveIdsAreStable();
  console.log('[OK] Stable board objective IDs passed');
  checkMidSeasonSackingTerminatesImmediately();
  console.log('[OK] Mid-season terminal sacking passed');
  checkNonTerminalSackingWarningDoesNotDismiss();
  console.log('[OK] Non-terminal sacking warning passed');
  checkSeasonEndSackingUsesSharedThreshold();
  console.log('[OK] Shared season-end sacking threshold passed');
  checkSeededFormationDiversity();
  console.log('[OK] Seeded formation diversity check passed');

  checkSanityMatchScores();
  console.log('[OK] Sanity Match Scores check passed');
  checkDisciplineRatesArePlausible();
  console.log('[OK] Discipline rate plausibility passed');
  checkQuickSimMatchSummaryIncludesStatsAndRatings();
  console.log('[OK] Quick-sim match summary checks passed');
  checkPenaltyShootoutUsesIndividualKicks();
  console.log('[OK] Individual penalty shootout checks passed');
  checkQuickSimKnockoutUsesExtraTimeBeforePenalties();
  console.log('[OK] Extra-time knockout tie checks passed');
  checkLeaguePlayoffFixtureDoesNotChangeTableStats();
  console.log('[OK] League play-off table accounting check passed');

  checkZustandStoreLiveMatchCleanup();
  console.log('[OK] Zustand Live Match cleanup check passed');

  checkRosterSizeConstraints();
  console.log('[OK] Roster Size constraints check passed');

  checkManualTransfersRespectWindow();
  console.log('[OK] Manual transfer window guard passed');
  checkManualTransfersRejectNonFiniteMoney();
  console.log('[OK] Manual transfer finite money guard passed');
  checkApproachUnlistedBackupCreatesPendingNegotiation();
  console.log('[OK] Unlisted player approach negotiation passed');
  checkApproachCoreNeededPlayerRejectsWithoutNegotiation();
  console.log('[OK] Core-player approach rejection passed');
  checkListedUnderAskCreatesCounterNegotiationWithoutMove();
  console.log('[OK] Listed-player counter negotiation passed');
  checkAcceptCounterMovesPlayerAndMarksNegotiationAccepted();
  console.log('[OK] Accept transfer counter passed');
  checkWeeklyNegotiationsExpireAfterDeadline();
  console.log('[OK] Weekly negotiation expiry passed');
  checkRivalBidWinsWhenUserDoesNotMatch();
  console.log('[OK] Rival transfer bid resolution passed');
  checkActiveNegotiationsCanBeWithdrawnInUi();
  console.log('[OK] Active negotiation withdrawal UI passed');
  checkManualFreeAgentSigningMovesPlayerDuringWindow();
  console.log('[OK] Manual free-agent signing passed');
  checkManualFreeAgentSigningWorksOutsideWindow();
  console.log('[OK] Manual free-agent outside-window signing passed');
  checkManualFreeAgentSigningRejectsFullSquad();
  console.log('[OK] Manual free-agent squad-cap guard passed');
  checkUnavailableBenchPlayersCanBeRemoved();
  console.log('[OK] Unavailable bench player cleanup passed');
  checkRecoveredSelectedBenchDoesNotOverflow();
  console.log('[OK] Recovered selected bench overflow guard passed');
  checkLineupActionsPreserveBenchLimit();
  console.log('[OK] Lineup action bench limit passed');
  checkPlayerRoleCompatibilityMatrix();
  console.log('[OK] Player role compatibility matrix passed');
  checkSlotKeyedPlayerRoleLookup();
  console.log('[OK] Slot-keyed player role lookup passed');
  checkPlayerRolesAdjustShapeProfile();
  console.log('[OK] Player role shape adjustments passed');
  checkMatchRuntimeUsesPlayerRoles();
  console.log('[OK] Match runtime role integration guard passed');
  checkPlayerRoleEnergyDrainModifiers();
  console.log('[OK] Player role energy drain modifiers passed');
  checkRolePickerShowsRoleEffects();
  console.log('[OK] Role picker effect descriptions passed');
  checkLineupInboxActionFiltersStaleFormationMap();
  console.log('[OK] Lineup inbox stale formation map check passed');
  checkSeasonReportsUseCompetitionLifecycleAndLeagueTables();
  console.log('[OK] Season reporting lifecycle guards passed');
  checkAiTransferListingsExpireOutsideWindow();
  console.log('[OK] AI transfer listing expiry passed');
  checkAiBuyerAtMaximumSquadSizeCannotBuy();
  console.log('[OK] AI transfer maximum squad guard passed');
  checkAiSignsFreeAgentForUrgentSquadNeed();
  console.log('[OK] AI free-agent signing passed');
  checkAiStaleListedTargetIsRevalidated();
  console.log('[OK] AI stale listing revalidation passed');
  checkEliteAiRejectsUnderStandardTarget();
  console.log('[OK] AI elite target quality guard passed');
  checkExperiencedAiPrefersOlderEqualTarget();
  console.log('[OK] AI experienced target preference passed');
  checkAiTransferRespectsOperatingWageAffordability();
  console.log('[OK] AI wage affordability guard passed');
  checkSeasonEndProgressionUpdatesMatchAbility();
  console.log('[OK] Season-end player progression ability update passed');
  checkWeeklyTrainingFocusRaisesFocusedStat();
  console.log('[OK] Weekly training focus progression passed');
  checkTrainingRespectsPotentialCap();
  console.log('[OK] Training potential cap passed');
  checkSeasonEndProgressionRespectsPotentialCap();
  console.log('[OK] Season-end potential cap passed');
  checkYouthIntakeAssignsHiddenPotential();
  console.log('[OK] Youth hidden potential assignment passed');
  checkSeededPlayersNormalizeTraits();
  console.log('[OK] Seeded trait normalization passed');
  checkTraitRegistryCoversSeededTraits();
  console.log('[OK] Trait registry seed coverage passed');
  checkTraitBonusesExposeMechanicalEffects();
  console.log('[OK] Trait mechanical effects passed');
  checkTraitTrainingFocusAddsXp();
  console.log('[OK] Trait training XP integration passed');
  checkRelentlessTraitReducesFatiguePenalty();
  console.log('[OK] Trait fatigue integration passed');
  checkWeeklyRevenueUsesDivisionAndSponsorRates();
  console.log('[OK] Weekly revenue breakdown passed');
  checkWeeklyProgressionAppliesRevenueBreakdown();
  console.log('[OK] Weekly finance progression passed');
  checkContractDeparturesPreferViableDestinations();
  console.log('[OK] Contract departure destination quality passed');
  checkFreeAgentSaveReloadEquivalence();
  console.log('[OK] Free-agent save/reload equivalence passed');
  checkSeasonRolloverReplenishesMinimumSquadAndGoalkeepers();
  console.log('[OK] Season rollover replenishment coverage passed');
  checkSimultaneousExpiriesRecomputeAgainstProvisionalSquad();
  console.log('[OK] Simultaneous contract expiry recomputation passed');
  checkUiContractsMatchEngineState();
  console.log('[OK] UI data contract checks passed');
  checkInitialGameSetupCanBeSeeded();
  console.log('[OK] Seeded initial game setup passed');
  checkStoreInitializesSelectedTeamDefaults();
  console.log('[OK] Selected team initialization defaults passed');
  checkTacticalAdaptationRunsOncePerPlayedCount();
  console.log('[OK] Tactical adaptation repeat guard passed');
  checkTacticalAdaptationIgnoresUnavailablePlayers();
  console.log('[OK] Tactical adaptation availability check passed');
  checkMatchRatingsIncludeIndividualOutput();
  console.log('[OK] Match rating contribution checks passed');
  checkCleanSheetRatingsUsePlayerWindow();
  console.log('[OK] Windowed clean-sheet rating check passed');
  checkValidationCatchesPastUnplayedFixturesAndNonFiniteFinances();
  console.log('[OK] Agent validation coverage checks passed');

  console.log('--- REGRESSION CHECKS COMPLETE ---');
};

runRegressionChecks();
