// Aggregated regression runner. Checks are split by domain into
// ./calendar, ./match, ./transfer, ./board, ./persistence, ./live-match, ./squad.
// Execution order matches the original scripts/regression_checks.ts runner.
import { checkFormationSlotLookupUsesExactFormation, checkFormationMapRejectsWrongPositions, checkSeededFormationDiversity, checkRosterSizeConstraints, checkUnavailableBenchPlayersCanBeRemoved, checkRecoveredSelectedBenchDoesNotOverflow, checkLineupActionsPreserveBenchLimit, checkLineupInboxActionFiltersStaleFormationMap, checkTacticalAdaptationRunsOncePerPlayedCount, checkTacticalAdaptationIgnoresUnavailablePlayers } from './squad';
import { checkCleanSheetWindows, checkPossessionFlowIsNotStrictAlternation, checkBranchGuards, checkSanityMatchScores, checkDisciplineRatesArePlausible, checkQuickSimMatchSummaryIncludesStatsAndRatings, checkMatchRatingsIncludeIndividualOutput, checkCleanSheetRatingsUsePlayerWindow } from './match';
import { checkLiveSentOffMinutes, checkLiveSubstitutionsApplyBeforeFullTime, checkUserAiDoesNotSpendLiveSubstitutions, checkManualLiveSubstitutionAndShapeAreMatchLocal, checkManualLiveSubstitutionValidation, checkLiveMatchSummaryIncludesStatsAndRatings, checkActiveLiveMatchBlocksWeekAdvance, checkStaleLiveMatchRecovery, checkDirectFinishCompletesUnprocessedLiveMatch, checkZustandStoreLiveMatchCleanup } from './live-match';
import { checkCompetitionPanelHandlesMissingTeam, checkDivisionBootstrap, checkPromotionRelegation, checkSeasonReportsUseCompetitionLifecycleAndLeagueTables, checkSeasonEndProgressionUpdatesMatchAbility, checkSeasonRolloverReplenishesMinimumSquadAndGoalkeepers } from './calendar';
import { checkUserTeamProgressionDoesNotAdaptFormation, checkManagerProfilesLoaded, checkActiveCupRoundCountsAsReached, checkBoardObjectiveIdsAreStable, checkMidSeasonSackingTerminatesImmediately, checkNonTerminalSackingWarningDoesNotDismiss, checkSeasonEndSackingUsesSharedThreshold, checkUiContractsMatchEngineState, checkInitialGameSetupCanBeSeeded, checkStoreInitializesSelectedTeamDefaults } from './board';
import { checkManualTransfersRespectWindow, checkManualTransfersRejectNonFiniteMoney, checkAiTransferListingsExpireOutsideWindow, checkAiBuyerAtMaximumSquadSizeCannotBuy, checkAiStaleListedTargetIsRevalidated, checkEliteAiRejectsUnderStandardTarget, checkExperiencedAiPrefersOlderEqualTarget, checkAiTransferRespectsOperatingWageAffordability, checkContractDeparturesPreferViableDestinations, checkSimultaneousExpiriesRecomputeAgainstProvisionalSquad } from './transfer';
import { checkFreezeRecoveryControlsAreVisible, checkStaleFormationMapRecoveryModel, checkFreeAgentSaveReloadEquivalence, checkValidationCatchesPastUnplayedFixturesAndNonFiniteFinances } from './persistence';

const runRegressionChecks = () => {
  console.log('--- ENGINE REGRESSION CHECKS ---');
  checkFormationSlotLookupUsesExactFormation();
  console.log('[OK] Exact formation slot lookup passed');
  checkCleanSheetWindows();
  console.log('[OK] Clean-sheet window checks passed');
  checkLiveSentOffMinutes();
  console.log('[OK] Live sent-off minute check passed');
  checkPossessionFlowIsNotStrictAlternation();
  console.log('[OK] Possession flow variability guard passed');
  checkLiveSubstitutionsApplyBeforeFullTime();
  console.log('[OK] Live in-match substitution check passed');
  checkUserAiDoesNotSpendLiveSubstitutions();
  console.log('[OK] User live AI-substitution guard passed');
  checkManualLiveSubstitutionAndShapeAreMatchLocal();
  console.log('[OK] Manual live substitution and shape locality passed');
  checkManualLiveSubstitutionValidation();
  console.log('[OK] Manual live substitution validation passed');
  checkLiveMatchSummaryIncludesStatsAndRatings();
  console.log('[OK] Live match summary checks passed');
  checkActiveLiveMatchBlocksWeekAdvance();
  console.log('[OK] Active live match week-advance guard passed');
  checkStaleLiveMatchRecovery();
  console.log('[OK] Stale live-match recovery passed');
  checkDirectFinishCompletesUnprocessedLiveMatch();
  console.log('[OK] Direct live-match finish completion passed');
  checkCompetitionPanelHandlesMissingTeam();
  console.log('[OK] Competition panel missing-team fallback passed');
  checkFreezeRecoveryControlsAreVisible();
  console.log('[OK] Freeze recovery controls passed');
  checkBranchGuards();
  console.log('[OK] Second-yellow and shape parity guards passed');
  checkUserTeamProgressionDoesNotAdaptFormation();
  console.log('[OK] User team tactical adaptation guard passed');
  checkManagerProfilesLoaded();
  console.log('[OK] Manager profile loading passed');
  checkDivisionBootstrap();
  console.log('[OK] Division bootstrap check passed');
  checkPromotionRelegation();
  console.log('[OK] Promotion and relegation checks passed');
  checkStaleFormationMapRecoveryModel();
  console.log('[OK] Stale formation-map recovery model passed');
  checkFormationMapRejectsWrongPositions();
  console.log('[OK] Wrong-position formation-map recovery passed');
  checkActiveCupRoundCountsAsReached();
  console.log('[OK] Active cup-round objective recognition passed');
  checkBoardObjectiveIdsAreStable();
  console.log('[OK] Stable board objective IDs passed');
  checkMidSeasonSackingTerminatesImmediately();
  console.log('[OK] Mid-season terminal sacking passed');
  checkNonTerminalSackingWarningDoesNotDismiss();
  console.log('[OK] Non-terminal sacking warning passed');
  checkSeasonEndSackingUsesSharedThreshold();
  console.log('[OK] Shared season-end sacking threshold passed');
  checkSeededFormationDiversity();
  console.log('[OK] Seeded formation diversity check passed');

  checkSanityMatchScores();
  console.log('[OK] Sanity Match Scores check passed');
  checkDisciplineRatesArePlausible();
  console.log('[OK] Discipline rate plausibility passed');
  checkQuickSimMatchSummaryIncludesStatsAndRatings();
  console.log('[OK] Quick-sim match summary checks passed');

  checkZustandStoreLiveMatchCleanup();
  console.log('[OK] Zustand Live Match cleanup check passed');

  checkRosterSizeConstraints();
  console.log('[OK] Roster Size constraints check passed');

  checkManualTransfersRespectWindow();
  console.log('[OK] Manual transfer window guard passed');
  checkManualTransfersRejectNonFiniteMoney();
  console.log('[OK] Manual transfer finite money guard passed');
  checkUnavailableBenchPlayersCanBeRemoved();
  console.log('[OK] Unavailable bench player cleanup passed');
  checkRecoveredSelectedBenchDoesNotOverflow();
  console.log('[OK] Recovered selected bench overflow guard passed');
  checkLineupActionsPreserveBenchLimit();
  console.log('[OK] Lineup action bench limit passed');
  checkLineupInboxActionFiltersStaleFormationMap();
  console.log('[OK] Lineup inbox stale formation map check passed');
  checkSeasonReportsUseCompetitionLifecycleAndLeagueTables();
  console.log('[OK] Season reporting lifecycle guards passed');
  checkAiTransferListingsExpireOutsideWindow();
  console.log('[OK] AI transfer listing expiry passed');
  checkAiBuyerAtMaximumSquadSizeCannotBuy();
  console.log('[OK] AI transfer maximum squad guard passed');
  checkAiStaleListedTargetIsRevalidated();
  console.log('[OK] AI stale listing revalidation passed');
  checkEliteAiRejectsUnderStandardTarget();
  console.log('[OK] AI elite target quality guard passed');
  checkExperiencedAiPrefersOlderEqualTarget();
  console.log('[OK] AI experienced target preference passed');
  checkAiTransferRespectsOperatingWageAffordability();
  console.log('[OK] AI wage affordability guard passed');
  checkSeasonEndProgressionUpdatesMatchAbility();
  console.log('[OK] Season-end player progression ability update passed');
  checkContractDeparturesPreferViableDestinations();
  console.log('[OK] Contract departure destination quality passed');
  checkFreeAgentSaveReloadEquivalence();
  console.log('[OK] Free-agent save/reload equivalence passed');
  checkSeasonRolloverReplenishesMinimumSquadAndGoalkeepers();
  console.log('[OK] Season rollover replenishment coverage passed');
  checkSimultaneousExpiriesRecomputeAgainstProvisionalSquad();
  console.log('[OK] Simultaneous contract expiry recomputation passed');
  checkUiContractsMatchEngineState();
  console.log('[OK] UI data contract checks passed');
  checkInitialGameSetupCanBeSeeded();
  console.log('[OK] Seeded initial game setup passed');
  checkStoreInitializesSelectedTeamDefaults();
  console.log('[OK] Selected team initialization defaults passed');
  checkTacticalAdaptationRunsOncePerPlayedCount();
  console.log('[OK] Tactical adaptation repeat guard passed');
  checkTacticalAdaptationIgnoresUnavailablePlayers();
  console.log('[OK] Tactical adaptation availability check passed');
  checkMatchRatingsIncludeIndividualOutput();
  console.log('[OK] Match rating contribution checks passed');
  checkCleanSheetRatingsUsePlayerWindow();
  console.log('[OK] Windowed clean-sheet rating check passed');
  checkValidationCatchesPastUnplayedFixturesAndNonFiniteFinances();
  console.log('[OK] Agent validation coverage checks passed');

  console.log('--- REGRESSION CHECKS COMPLETE ---');
};

runRegressionChecks();
